modLoader="javafml"
loaderVersion="[36,)"
license="BSD 3-Clause \"New\" or \"Revised\" License"
issueTrackerURL="https://github.com/SanAndreasP/SanLib/issues"

[[mods]]
    modId="sanlib"
    version="$version"
    displayName="$name"
    logoFile="logo.png"
    authors="SanAndreasP"
    description='''
    A library made for and required by all my mods.
    '''
    [[dependencies.sanlib]]
        modId="forge"
        mandatory=true
        versionRange="[36,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.sanlib]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.5,1.17)"
        ordering="NONE"
        side="BOTH"

[[mods]]
    modId="sanplayermodel"
    version="$pm_version"
    displayName="$pm_name"
    authors="SanAndreasP"
    description='''
    A mod that's just adding a custom player model for myself.
    '''
    [[dependencies.sanplayermodel]]
        modId="sanlib"
        mandatory=true
        versionRange="[2.0.0,)"
        ordering="AFTER"
        side="CLIENT"