modLoader="javafml"
loaderVersion="[35,)"
license="BSD 3-Clause \"New\" or \"Revised\" License"
issueTrackerURL="https://github.com/SanAndreasP/SanLib/issues"

[[mods]]
    modId="sanlib"
    version="0"
    displayName="SL"
    authors="SanAndreasP"
    description=''''''

[[mods]]
    modId="santest"
    version="0"
    displayName="SL"
    authors="SanAndreasP"
    description=''''''